import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import prettier from 'eslint-config-prettier';

/**
 * Constitution, Development Workflow: "code style is machine-enforced and never debated in review
 * ... Analyzer and lint violations fail the build." Nothing here is advisory.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      // Generated by Orval from the BFF's OpenAPI document (ADR-0004). Linting output nobody
      // hand-edits produces noise the author cannot act on; drift is caught by the codegen check
      // instead.
      'packages/api-client/src/generated/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,

      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // Principle IX: `any` requires a written justification. An error (not a warning) is what
      // makes that literal — silencing it takes an eslint-disable line, which is where the
      // justification goes and what a reviewer can see.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },

  // Last, so formatting rules never fight Prettier.
  prettier,
);
