// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Api.Data;

#nullable disable

namespace Products.Api.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20260816085315_SeedCatalog")]
    partial class SeedCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Products.Api.Data.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f8d6b1e-0001-4000-8000-000000000001"),
                            Name = "Field Notes Notebook",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = new Guid("9f8d6b1e-0001-4000-8000-000000000002"),
                            Name = "Ceramic Pour-Over Set",
                            Price = 48.00m
                        },
                        new
                        {
                            Id = new Guid("9f8d6b1e-0001-4000-8000-000000000003"),
                            Name = "Linen Apron",
                            Price = 34.25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
